---
title: "env_cad_test"
author: "Lambert De Monte - 260746902"
date: "24 mars 2020"
output: html_document
---

```{r, include=FALSE}
library(tinytex)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(kableExtra)
library(purrr)
library(rlist)
library(evd)
library(ismev)
library(fExtremes)
library(evmix)
```

```{r, warning=FALSE, results=FALSE}
df_qc <- read_csv("../Datasets/QC_1943_2020.csv")
names(df_qc)[names(df_qc) == "Date/Time"] <- "Date_Time"
names(df_qc)[names(df_qc) == "Max Temp (°C)"] <- "Max_Temp"
names(df_qc)[names(df_qc) == "Total Precip (mm)"] <- "Total_Rain_mm"
df_qc <- df_qc %>% mutate(.,city=1)

df_mtl <- read_csv("../Datasets/MTL_1941_2020.csv")
names(df_mtl)[names(df_mtl) == "Date/Time"] <- "Date_Time"
names(df_mtl)[names(df_mtl) == "Max Temp (°C)"] <- "Max_Temp"
names(df_mtl)[names(df_mtl) == "Total Precip (mm)"] <- "Total_Rain_mm"
df_mtl <- df_mtl %>% mutate(.,city=2)

df_tr <- read_csv("../Datasets/TR_1937_2020.csv") 
names(df_tr)[names(df_tr) == "Date/Time"] <- "Date_Time"
names(df_tr)[names(df_tr) == "Max Temp (°C)"] <- "Max_Temp"
names(df_tr)[names(df_tr) == "Total Precip (mm)"] <- "Total_Rain_mm"
df_tr <- df_tr %>% mutate(.,city=3)

df_vc <- read_csv("../Datasets/VC_1937_2020.csv")
names(df_vc)[names(df_vc) == "Date/Time"] <- "Date_Time"
names(df_vc)[names(df_vc) == "Max Temp (°C)"] <- "Max_Temp"
names(df_vc)[names(df_vc) == "Total Precip (mm)"] <- "Total_Rain_mm"
df_vc <- df_vc %>% mutate(.,city=4)



df <- rbind(df_mtl,df_qc)
df <- rbind(df,df_vc)
df <- rbind(df,df_tr)
df <- drop_na(df,Max_Temp) %>% group_by(Date_Time,city) %>% top_n(1, Max_Temp)
df <- df %>% filter(.,Month==7)
```


#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################
                                                                                   BLOCK MAXIMA APPROACH
#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################

```{r}
df_bm <- df %>% group_by(Year,city)  %>% summarise(.,max = max(Max_Temp)) %>% drop_na(.)
```

```{r}
#Function that computes return levels and 95% confidence interval for different return levels
return_levels_bm <- function(df_bm,levels){
  
  ret_lev = list()
  conf_int = list()
  city = list()
  levs = list()
  
  for(j in 1:4){
    df_temp <- df_bm %>% filter(.,city==j)
    model <- fgev(x=df_temp$max)
    
    mu <- model$estimate[[1]]
    sig <- model$estimate[[2]]
    xi <- model$estimate[[3]]  
    
    for(i in 1:length(levels)){
      
      p <- 1.0/levels[i]
      Zp <- mu - (sig/xi)*(1-(-log(1-p))^(-1*xi))
      a <- (-1/xi)*(1-(-log(1-p))^(-1*xi))
      yp = -log(1-p)
      b <-  (sig / (xi^2)) * (1 - yp^(-1*xi)) - (sig / (xi)) * ( yp^(-1*xi)) * log(yp)
      grad_Zp <- c(1, a, b)
      var_Zp <- t(grad_Zp) %*% model$var.cov %*% grad_Zp
      conf <- 1.96*sqrt(var_Zp)
      
      ret_lev[length(ret_lev)+1] <- Zp
      conf_int[length(conf_int)+1] <- conf
      city[length(city)+1] <- j
      levs[length(levs)+1] <- levels[i]
    }
    #add the infinite return level
    ret_lev[length(ret_lev)+1] <- mu - sig/xi
    a <- (-1/xi)
    b <-  (sig / (xi^2))
    grad_Zp <- c(1, a, b)
    var_Z_0 <- t(grad_Zp) %*% model$var.cov %*% grad_Zp
    conf_int[length(conf_int)+1] <- 1.96*sqrt(var_Z_0)
    city[length(city)+1] <- j
    levs[length(levs)+1] <- 0
  }
  
  df <- data.frame(cbind(unlist(city),unlist(levs),unlist(ret_lev),unlist(conf_int)))
  names(df) <- c("city","p","Return_level","Confidence_int")
  return (df)
}
```

```{r}
levels <- append(c(2:10),c(20,25,50,75,100))
df_bm_fin <- return_levels_bm(df_bm,levels)
df_bm_fin
```

```{r}
ggplot(df_bm_fin, aes(x=p, y= Return_level,col=factor(city, levels=c(1,2,3,4), labels=c("Quebec", "Montreal", "Toronto", "Vancouver")))) + geom_point() + xlab("Number of Years") + ylab("Return Level") + geom_ribbon(data=filter(df_bm_fin,p>0),aes(ymin=(Return_level - Confidence_int),ymax=(Return_level + Confidence_int),fill=factor(city, levels=c(1,2,3,4), labels=c("Quebec", "Montreal", "Toronto", "Vancouver"))),alpha=0.3) + guides(fill = FALSE) + ggtitle("Return Levels for Maxima of Temperature in July\nfor Cities in Canada") + theme(plot.title = element_text(size=18, face="bold", margin = margin(10, 0, 10, 0))) + theme(axis.text.x=element_text(angle=0, size=12, vjust=0.5)) + theme(axis.text.y=element_text(angle=0, size=12, vjust=0.5)) + theme(
  axis.title.x = element_text(size = 14,color="black", vjust=-0.35),
      axis.title.y = element_text(size = 14,color="black" , vjust=0.35)   
          ) + scale_color_discrete(name="")  + scale_fill_manual(values=c("#FFCC00", "#FF6600","#990000" ,"009900")) + scale_color_manual(values=c("#FFCC00", "#FF6600","#990000" ,"009900"),name="")
```


#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################
                                                                            r-LARGEST ORDER STATISTIC APPROACH
#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################

No comparisons for reasons detailed in the report.

#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################
                                                                                  THRESHOLD MODEL APPROACH
#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################
#########################################################################################################################################################################################

```{r}
#Function that computes return levels and 95% confidence interval for different return levels
return_levels_thresh <- function(obs,city_k,u,levels){
  
  ret_lev = list()
  conf_int = list()
  levs = list()
  thresh = list()
  city = list()
  
  for(j in 1:length(u)){
    u_0 <- u[j]
    model = gpdFit(obs, u = u_0)
    sig <- model@fit$par.ests[2]
    xi <- model@fit$par.ests[1]
    V <- model@fit$varcov
    V[1,1] <- model@fit$varcov[2,2]
    V[2,2] <- model@fit$varcov[1,1]
    sampl_prop <- length(obs[obs>u_0])/length(obs)
    
    A <- matrix(rep(0,9),nrow=3,ncol=3)
    A[2:3,2:3] <- V
    A[1,1] <- sampl_prop*(1-sampl_prop)/length(obs)
    
    for(i in 1:length(levels)){
      m <- levels[i]*31
      
      x_m <- u_0 + (sig/xi)*((m*sampl_prop)^xi -1)
      d_samp <- sig*(m^xi)*(sampl_prop^(xi-1))
      d_sig <- (xi^(-1))*(((m*sampl_prop)^xi) -1) 
      d_xi <- -1*(sig/(xi^2))*(((m*sampl_prop)^xi) -1) + (sig/xi)*((m*sampl_prop)^xi)*log(m*sampl_prop)
      grad <- c(d_samp,d_sig,d_xi)
      sd_err <- sqrt(t(grad) %*% A %*% grad)
      
      ret_lev[length(ret_lev)+1] <- x_m
      conf_int[length(conf_int)+1] <- 1.96*sd_err
      levs[length(levs)+1] <- levels[i]
      thresh[length(thresh)+1] <- u_0
      city[length(city)+1] <- city_k
    }
  }

  df <- data.frame(cbind(unlist(city),unlist(thresh),unlist(levs),unlist(ret_lev),unlist(conf_int)))
  names(df) <- c("city", "u","m","Return_level","Confidence_int")
  return (df)
}
```

```{r}
city_k <- 1
u_0 <- c(28.5)
df_temp <- filter(df,city==city_k)
obs <- df_temp$Max_Temp
levels <- append(c(2:10),c(20,25,50,75,100))
df_u_qc <- return_levels_thresh(obs,city_k,u_0,levels)

city_k <- 2
u_0 <- c(28)
df_temp <- filter(df,city==city_k)
obs <- df_temp$Max_Temp
levels <- append(c(2:10),c(20,25,50,75,100))
df_u_mtl <- return_levels_thresh(obs,city_k,u_0,levels)

city_k <- 3
u_0 <- c(29.5)
df_temp <- filter(df,city==city_k)
obs <- df_temp$Max_Temp
levels <- append(c(2:10),c(20,25,50,75,100))
df_u_tr <- return_levels_thresh(obs,city_k,u_0,levels)

city_k <- 4
u_0 <- c(25)
df_temp <- filter(df,city==city_k)
obs <- df_temp$Max_Temp
levels <- append(c(2:10),c(20,25,50,75,100))
df_u_vc <- return_levels_thresh(obs,city_k,u_0,levels)
```

```{r}
df_thresh <- rbind(df_u_qc,df_u_mtl)
df_thresh <- rbind(df_thresh,df_u_tr)
df_thresh <- rbind(df_thresh,df_u_vc)
df_thresh
```

```{r}
ggplot(df_thresh, aes(x=m, y= Return_level,col=factor(city, levels=c(1,2,3,4), labels=c("Quebec", "Montreal", "Toronto", "Vancouver")))) + geom_point() + xlab("Number of Years") + ylab("Return Level") + geom_ribbon(data=filter(df_thresh,m>0),aes(ymin=(Return_level - Confidence_int),ymax=(Return_level + Confidence_int),fill=factor(city, levels=c(1,2,3,4), labels=c("Quebec", "Montreal", "Toronto", "Vancouver"))),alpha=0.3) + guides(fill = FALSE) + ggtitle("Return Levels for Maxima of Temperature in July\nfor Cities in Canada") + theme(plot.title = element_text(size=18, face="bold", margin = margin(10, 0, 10, 0))) + theme(axis.text.x=element_text(angle=0, size=12, vjust=0.5)) + theme(axis.text.y=element_text(angle=0, size=12, vjust=0.5)) + theme(
  axis.title.x = element_text(size = 14,color="black", vjust=-0.35),
      axis.title.y = element_text(size = 14,color="black" , vjust=0.35)   
          ) + scale_color_discrete(name="")  + scale_fill_manual(values=c("#FFCC00", "#FF6600","#990000" ,"009900")) + scale_color_manual(values=c("#FFCC00", "#FF6600","#990000" ,"009900"),name="")
```

```{r}
df_thresh_mod <- df_thresh %>% mutate(city_1 = city + 4) %>% dplyr::select(.,city_1,m,Return_level,Confidence_int) 
names(df_thresh_mod) <- c("city","p","Return_level","Confidence_int")
df_final <- rbind(df_bm_fin,df_thresh_mod)
df_final
```


```{r}
ggplot(df_final, aes(x=p, y= Return_level,col=factor(city, levels=c(1,2,3,4,5,6,7,8), labels=c("Quebec BM", "Montreal BM", "Toronto BM", "Vancouver BM","Quebec T", "Montreal T", "Toronto T", "Vancouver T")))) + geom_point() + xlab("Number of Years") + ylab("Return Level") + geom_ribbon(data=filter(df_final,p>0),aes(ymin=(Return_level - Confidence_int),ymax=(Return_level + Confidence_int),fill=factor(city, levels=c(1,2,3,4,5,6,7,8), labels=c("Quebec BM", "Montreal BM", "Toronto BM", "Vancouver BM","Quebec T", "Montreal T", "Toronto T", "Vancouver T"))),alpha=0.3) + guides(fill = FALSE) + ggtitle("Return Levels for Maxima of Temperature in July\nfor Cities in Canada") + theme(plot.title = element_text(size=18, face="bold", margin = margin(10, 0, 10, 0))) + theme(axis.text.x=element_text(angle=0, size=12, vjust=0.5)) + theme(axis.text.y=element_text(angle=0, size=12, vjust=0.5)) + theme(
  axis.title.x = element_text(size = 14,color="black", vjust=-0.35),
      axis.title.y = element_text(size = 14,color="black" , vjust=0.35)   
          ) + scale_color_discrete(name="") + scale_fill_manual(values=c("#FFCC00", "#FF6600","#990000" ,"009900","#FFCC00", "#FF6600","#990000" ,"009900")) + scale_color_manual(values=c("#FFCC00", "#FF6600","#990000" ,"009900","#FFCC00", "#FF6600","#990000" ,"009900"),name="")
```